//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from AzSQL.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="AzSQLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public interface IAzSQLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AzSQLParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] AzSQLParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AzSQLParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] AzSQLParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AzSQLParser.select_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelect_clause([NotNull] AzSQLParser.Select_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AzSQLParser.select_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelect_clause([NotNull] AzSQLParser.Select_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AzSQLParser.column_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_list([NotNull] AzSQLParser.Column_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AzSQLParser.column_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_list([NotNull] AzSQLParser.Column_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AzSQLParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColumn_name([NotNull] AzSQLParser.Column_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AzSQLParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColumn_name([NotNull] AzSQLParser.Column_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AzSQLParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTable_name([NotNull] AzSQLParser.Table_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AzSQLParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTable_name([NotNull] AzSQLParser.Table_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AzSQLParser.where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhere_clause([NotNull] AzSQLParser.Where_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AzSQLParser.where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhere_clause([NotNull] AzSQLParser.Where_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="AzSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpr([NotNull] AzSQLParser.NotExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>notExpr</c>
	/// labeled alternative in <see cref="AzSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpr([NotNull] AzSQLParser.NotExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>paranthesizedExpr</c>
	/// labeled alternative in <see cref="AzSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParanthesizedExpr([NotNull] AzSQLParser.ParanthesizedExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>paranthesizedExpr</c>
	/// labeled alternative in <see cref="AzSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParanthesizedExpr([NotNull] AzSQLParser.ParanthesizedExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="AzSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrExpr([NotNull] AzSQLParser.OrExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>orExpr</c>
	/// labeled alternative in <see cref="AzSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrExpr([NotNull] AzSQLParser.OrExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>baseComparison</c>
	/// labeled alternative in <see cref="AzSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseComparison([NotNull] AzSQLParser.BaseComparisonContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>baseComparison</c>
	/// labeled alternative in <see cref="AzSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseComparison([NotNull] AzSQLParser.BaseComparisonContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="AzSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpr([NotNull] AzSQLParser.AndExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>andExpr</c>
	/// labeled alternative in <see cref="AzSQLParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpr([NotNull] AzSQLParser.AndExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AzSQLParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] AzSQLParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AzSQLParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] AzSQLParser.LiteralContext context);
}
